language: python

# python:
#   - 2.7
#   - 3.5
#   - 3.6

# Something in astropy/numpy breaks 3.5
matrix:
    include:
      - python: 3.6
        env:
            - NUMPY_VERSION=stable
            - ASTROPY_VERSION=stable
            - CONDA_DEPENDENCIES='scipy matplotlib pyyaml extinction dustmaps'
        
# commands to install dependencies (astropy, conda)
install: 
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

# command to run tests
script: 
    python setup.py test 